export const articles = [
    {id:"1", content:"first content", description:"first content, first content, first content,first content, first content"},
    {id:"2", content:"second content", description:"second content, second content, second content,second content, second content"},
    {id:"3", content:"third content", description:"third content, third content, third content,third content, third content"},
    {id:"4", content:"fourth content", description:"fourth content, fourth content, fourth content,fourth content, fourth content"},
    {id:"5", content:"fifth content", description:"fifth content, fifth content, fifth content,fifth content, fifth content"},
    {id:"6", content:"sixth content", description:"sixth content, sixth content, sixth content,sixth content, sixth content"},
    {id:"7", content:"seventh content", description:"seventh content, seventh content, seventh content,seventh content, seventh content"},
    {id:"8", content:"eight content", description:"eight content, eight content, eight content,eight content, eight content"},
    {id:"9", content:"ninth content", description:"ninth content, ninth content, ninth content,ninth content, ninth content"},
    {id:"10", content:"tenth content", description:"tenth content, tenth content, tenth content,tenth content, tenth content"},
    {id:"11", content:"eleventh content", description:"eleventh content, eleventh content, eleventh content, eleventh content, eleventh content"},
    {id:"12", content:"twelfth content", description:"twelfth content, twelfth content, twelfth content, twelfth content, twelfth content"},
    {id:"13", content:"thirteenth content", description:"thirteenth content, thirteenth content, thirteenth content, thirteenth content, thirteenth content"},
    {id:"14", content:"fourteenth content", description:"fourteenth content, fourteenth content, fourteenth content, fourteenth content, fourteenth content"},
    {id:"15", content:"fifteenth content", description:"fifteenth content, fifteenth content, fifteenth content, fifteenth content, fifteenth content"},
    {id:"16", content:"sixteenth content", description:"sixteenth content, sixteenth content, sixteenth content, sixteenth content, sixteenth content"},
    {id:"17", content:"seventeenth content", description:"seventeenth content, seventeenth content, seventeenth content, seventeenth content, seventeenth content"},
    {id:"18", content:"eighteenth content", description:"eighteenth content, eighteenth content, eighteenth content, eighteenth content, eighteenth content"},
    {id:"19", content:"nineteenth content", description:"nineteenth content, nineteenth content, nineteenth content, nineteenth content, nineteenth content"},
    {id:"20", content:"twentieth content", description:"twentieth content, twentieth content, twentieth content, twentieth content, twentieth content"},
    {id:"21", content:"twenty-first content", description:"twenty-first content, twenty-first content, twenty-first content, twenty-first content, twenty-first content"},
    {id:"22", content:"twenty-second content", description:"twenty-second content, twenty-second content, twenty-second content, twenty-second content, twenty-second content"},
    {id:"23", content:"twenty-third content", description:"twenty-third content, twenty-third content, twenty-third content, twenty-third content, twenty-third content"},
    {id:"24", content:"twenty-fourth content", description:"twenty-fourth content, twenty-fourth content, twenty-fourth content, twenty-fourth content, twenty-fourth content"},
    {id:"25", content:"twenty-fifth content", description:"twenty-fifth content, twenty-fifth content, twenty-fifth content, twenty-fifth content, twenty-fifth content"},
    {id:"26", content:"twenty-sixth content", description:"twenty-sixth content, twenty-sixth content, twenty-sixth content, twenty-sixth content, twenty-sixth content"},
    {id:"27", content:"twenty-seventh content", description:"twenty-seventh content, twenty-seventh content, twenty-seventh content, twenty-seventh content, twenty-seventh content"},
    {id:"28", content:"twenty-eighth content", description:"twenty-eighth content, twenty-eighth content, twenty-eighth content, twenty-eighth content, twenty-eighth content"},
    {id:"29", content:"twenty-ninth content", description:"twenty-ninth content, twenty-ninth content, twenty-ninth content, twenty-ninth content, twenty-ninth content"},
    {id:"30", content:"thirtieth content", description:"thirtieth content, thirtieth content, thirtieth content, thirtieth content, thirtieth content"}

]